version: '3.6'

services:
  postgres:
    image: postgres:10.16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      # use postgresql.conf in current directory
      - ${PWD}/postgresql.conf:/etc/postgresql/postgresql.conf:ro
  app:
    build: .
    depends_on:
      - postgres
